#!/bin/bash -e
#
# marinewatch-cli - command-line interface for Marinewatch

###########
## UTILS ##
###########

usage() {
    echo "Usage: $(basename $0) [-h] [-b <int>] [-c <string>] [-u <string>] [-d <string>] [-s] [-t]"
    echo ""
    echo "  -h  Help. Display this message and quit."
    echo "  -b  <int>  Run batch process with specified accuracy."
    echo "  -c  <string>  Run streaming process listening on specified address."
    echo "  -u  <string>  Create new database with name."
    echo "  -d  <string>  Start database with name."
    echo "  -s  Start web server."
    echo "  -t  Start streaming server."
    echo ""
    exit 1
}

batch() {
  docker-compose up -d cloudera &&
  docker-compose exec cloudera /bin/bash -lc "mvn package && spark-submit --packages com.databricks:spark-csv_2.10:1.5.0 --class com.foggly.mwspark.BatchProcess --master local[*] target/mwspark-0.0.1.jar $1"
}

streaming() {
  docker-compose up -d cloudera &&
  docker-compose exec cloudera /bin/bash -lc "mvn package && spark-submit --class com.foggly.mwspark.StreamingProcess --master local[*] target/mwspark-0.0.1.jar $1"
}

updatedb() {
  docker-compose up -d neo4j &&
  docker-compose exec neo4j /bin/bash -lc "bin/neo4j-admin import --database=$1.db --nodes /data-import/cells.csv --relationships /data-import/relationships.csv" &&
  docker-compose stop neo4j &&
  sed -i '' 's/NEO4J_dbms_active__database=.*/NEO4J_dbms_active__database='"$1"'.db/' neo4j.env &&
  docker-compose up -d neo4j &&
  echo "Waiting for neo4j to start..." &&
  sleep 5 &&
  docker-compose exec neo4j /bin/bash -lc "echo \"CREATE INDEX ON :Cell(latitude, longitude);\" | bin/cypher-shell"
}

startdb() {
  docker-compose stop neo4j &&
  sed -i '' 's/NEO4J_dbms_active__database=.*/NEO4J_dbms_active__database='"$1"'.db/' neo4j.env &&
  docker-compose up -d neo4j
}

webserver() {
  ruby ./code/web_api/app.rb
}

streamingserver() {
  ruby ./code/streaming_api/app.rb
}

##########
## MAIN ##
##########

if [[ $# -eq 0 ]] ; then
  usage
fi

while getopts "hb:c:u:d:st" optchar
do
    case "${optchar}" in
        h)
            usage
            ;;
        b)
            ACCURACY="$OPTARG"
            ;;
        c)
            STREAMING="$OPTARG"
            ;;
        s)
            WEBSERVER=1
            ;;
        t)
            STREAMINGSERVER=1
            ;;
        u)
            DATABASE="$OPTARG"
            ;;
        d)
            EXISTING_DATABASE="$OPTARG"
            ;;
        *)
            usage
            ;;
    esac
done

if [ ! -z "$ACCURACY" ]; then
  batch "$ACCURACY"
fi

if [ ! -z "$STREAMING" ]; then
  streaming "$STREAMING"
fi

if [ ! -z "$DATABASE" ]; then
  updatedb "$DATABASE"
fi

if [ ! -z "$EXISTING_DATABASE" ]; then
  startdb "$EXISTING_DATABASE"
fi

if [ ! -z "$WEBSERVER" ]; then
  webserver
fi

if [ ! -z "$STREAMINGSERVER" ]; then
  streamingserver
fi
